{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gameofthrones
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gameofthrones_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gameofthrones/gameofthrones_{{ version }}.tar.gz
  sha256: 932b7410249594a29381c7bff156bf2ec8acb2f2883e3286a34d211da827da82

build:
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-ggplot2 >=1.0.1
    - r-gridextra
  run:
    - r-base
    - r-mass
    - r-ggplot2 >=1.0.1
    - r-gridextra

test:
  commands:
    - $R -e "library('gameofthrones')"           # [not win]
    - "\"%R%\" -e \"library('gameofthrones')\""  # [win]

about:
  home: https://github.com/aljrico/gameofthrones
  license: MIT
  license_file: LICENSE
  summary: Implementation of the characteristic palettes from the TV show 'Game of Thrones'.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gameofthrones
# Type: Package
# Title: Palettes Inspired in the TV Show "Game of Thrones"
# Version: 1.0.0
# Authors@R: person("Alejandro", "Jimenez Rico", email = "aljrico@gmail.com", role = c("aut", "cre"))
# Maintainer: Alejandro Jimenez Rico <aljrico@gmail.com>
# Description: Implementation of the characteristic palettes from the TV show 'Game of Thrones'.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: TRUE
# Depends: R (>= 2.10)
# Suggests: hexbin (>= 1.27.0), testthat
# URL: https://github.com/aljrico/gameofthrones
# BugReports: https://github.com/aljrico/gameofthrones/issues
# Imports: ggplot2 (>= 1.0.1), gridExtra, MASS
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-12-19 13:19:46 UTC; aljrico
# Author: Alejandro Jimenez Rico [aut, cre]
# Repository: CRAN
# Date/Publication: 2018-12-30 23:30:06 UTC
