appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: F/fUckTzV8vPo8FHjGrrZPeYor62OoN9sOw4NK/0Xva74QtdeayP3ISJSLSvI/2Fii7ZhTFJm4zEnv3O5egWG21vGSMcibIUhNoFSKnGO3HyORP/LZLW5nUC/TkqXV/bEeuQkMq8/AepJxd1r0nATX1HNjjwiC8uD13DR7VXOJLH6ZlI8IWfb0PcxQs9UrTH5nCHI34gfBdw35HfOqnfHvlak9KyRCBdtxZrMLN7fHzffrJDrWWTLfAvlifCjuaF8bZs5PQzokL1teuwrQHrS0awcpgdAuCodgUEd/F0wcYFR0+KO6bxsY+CsoYy2Gssjdtizif/oRhHXGUpF669UudiSZkGBzVepez15ewhG5trhqWLpwP/AYS/UoW8ldvR8WnZJNnd5qR34EN1rVKB3cy9ktR8e9ryLduXvIYgJh3ey0ItsdqLkIbmwgHUdgWWTHygFWjydQP8J8HCBcdh6CSpSMSTo+WMGAcKcNHTl/MiDoKYVu8eQT1MyJsdAQlXRNeSrovWwYW66PH3RNS3hGzWtrQHu9kyaOmoCi04+8MHmjKOF+xtUo7wOFUSsQ/Q372p1Uwy//yAZQNaTWh8y3To3v7orPZe3vOYxb+Dcf23kXioRb5TgDaHDj+NmLD71Bnss8k0Mf7xAivIUJ+lrNl6gBGlh9qGLfok7hf+v4c=}
bot:
  automerge: true
